export type QuizTemplateOption = {
  label: string;
  emoji: string;
};

export type QuizTemplateQuestion = {
  question: string;
  options: QuizTemplateOption[];
};

export type QuizTemplate = {
  title: string;
  emoji: string;
  questions: QuizTemplateQuestion[];
};

export const quizTemplates: QuizTemplate[] = [
  {
    title: "Personal",
    emoji: "🔥",
    questions: [
      {
        question: "Cili është horoskopi im? ♈",
        options: [
          { label: "Dashi", emoji: "🐏" },
          { label: "Demi", emoji: "🐂" },
          { label: "Binjakët", emoji: "👯" },
          { label: "Gaforrja", emoji: "🦀" },
          { label: "Luani", emoji: "🦁" },
          { label: "Virgjëresha", emoji: "🌾" },
          { label: "Peshorja", emoji: "⚖️" },
          { label: "Akrepi", emoji: "🦂" },
          { label: "Shigjetari", emoji: "🏹" },
          { label: "Bricjapi", emoji: "🐐" },
          { label: "Ujori", emoji: "🌊" },
          { label: "Peshqit", emoji: "🐟" },
        ],
      },
      {
        question: "Cila është dita ime e preferuar? 📅",
        options: [
          { label: "E hënë", emoji: "🌧️" },
          { label: "E martë", emoji: "⚡" },
          { label: "E mërkurë", emoji: "📚" },
          { label: "E enjte", emoji: "☕" },
          { label: "E premte", emoji: "🔥" },
          { label: "E shtunë", emoji: "🎉" },
          { label: "E diel", emoji: "😌" },
        ],
      },
      {
        question: "Cila është ngjyra ime e preferuar? 🎨",
        options: [
          { label: "E zezë", emoji: "🖤" },
          { label: "Blu", emoji: "💙" },
          { label: "E kuqe", emoji: "❤️" },
          { label: "E bardhë", emoji: "🤍" },
          { label: "Jeshile", emoji: "💚" },
          { label: "Rozë", emoji: "🩷" },
          { label: "Vjollcë", emoji: "💜" },
          { label: "Gri", emoji: "🩶" },
        ],
      },
      {
        question: "Cili është ushqimi im i preferuar? 🍕",
        options: [
          { label: "Pizza", emoji: "🍕" },
          { label: "Burger", emoji: "🍔" },
          { label: "Pasta", emoji: "🍝" },
          { label: "Sushi", emoji: "🍣" },
          { label: "Taco", emoji: "🌮" },
          { label: "Byrek", emoji: "🥟" },
          { label: "Kebab", emoji: "🥙" },
          { label: "Patate", emoji: "🍟" },
        ],
      },
      {
        question: "Cili është artisti im i preferuar? 🎤",
        options: [
          { label: "Noizy", emoji: "🎙️" },
          { label: "Stresi", emoji: "🎧" },
          { label: "Ledri", emoji: "🎵" },
          { label: "Mozzik", emoji: "🔊" },
          { label: "Tayna", emoji: "💃" },
          { label: "Dafina", emoji: "✨" },
          { label: "Yll Limani", emoji: "🌟" },
          { label: "Elvana", emoji: "🎤" },
        ],
      },
      {
        question: "Ku dua të udhëtoj më shumë? ✈️",
        options: [
          { label: "Dubai", emoji: "🏙️" },
          { label: "Paris", emoji: "🗼" },
          { label: "USA", emoji: "🇺🇸" },
          { label: "Maldives", emoji: "🏝️" },
          { label: "Londër", emoji: "🇬🇧" },
          { label: "Milano", emoji: "🛍️" },
          { label: "Barcelona", emoji: "🌇" },
          { label: "Tokyo", emoji: "🗾" },
        ],
      },
      {
        question: "Çfarë më nervozon më shumë? 😤",
        options: [
          { label: "Gënjeshtra", emoji: "🤥" },
          { label: "Vonimi", emoji: "⏰" },
          { label: "Injorimi", emoji: "🙄" },
          { label: "Zhurma", emoji: "🔊" },
          { label: "Mosrespekti", emoji: "🚫" },
          { label: "Hipokrizia", emoji: "🎭" },
          { label: "Tradhtia", emoji: "💔" },
          { label: "Kaosi", emoji: "🌀" },
        ],
      },
      {
        question: "Çfarë bëj në kohë të lirë? 🎮",
        options: [
          { label: "Dal", emoji: "🚶" },
          { label: "Netflix", emoji: "📺" },
          { label: "Gaming", emoji: "🎮" },
          { label: "Fle", emoji: "😴" },
          { label: "Muzikë", emoji: "🎶" },
          { label: "Palestër", emoji: "🏋️" },
          { label: "Scroll", emoji: "📱" },
          { label: "Drive", emoji: "🚗" },
        ],
      },
      {
        question: "Si më përshkruajnë më shpesh? 😎",
        options: [
          { label: "I qetë", emoji: "😌" },
          { label: "Funny", emoji: "😂" },
          { label: "Lider", emoji: "👑" },
          { label: "I çmendur", emoji: "🤪" },
          { label: "Karizmatik", emoji: "✨" },
          { label: "Misterioz", emoji: "🌙" },
          { label: "Serioz", emoji: "🧠" },
          { label: "Dominant", emoji: "🔥" },
        ],
      },
      {
        question: "Çfarë më pëlqen më shumë? 🔥",
        options: [
          { label: "Party", emoji: "🎉" },
          { label: "Qetësi", emoji: "🕊️" },
          { label: "Sport", emoji: "⚽" },
          { label: "Udhetime", emoji: "✈️" },
          { label: "Makina", emoji: "🚘" },
          { label: "Moda", emoji: "🕶️" },
          { label: "Muzika", emoji: "🎵" },
          { label: "Puna", emoji: "💼" },
        ],
      },
    ],
  },
  {
    title: "Fun",
    emoji: "😂",
    questions: [
      {
        question: "Në party unë jam? 🕺",
        options: [
          { label: "DJ", emoji: "🎧" },
          { label: "I dehur", emoji: "🍻" },
          { label: "Qesharak", emoji: "😂" },
          { label: "I humbur", emoji: "😵" },
          { label: "Lider", emoji: "👑" },
          { label: "Duke kërcyer", emoji: "💃" },
          { label: "Duke filmuar", emoji: "📸" },
          { label: "Duke ikur herët", emoji: "🚪" },
        ],
      },
      {
        question: "Kur më shkruan dikush… 📱",
        options: [
          { label: "Reply direkt", emoji: "⚡" },
          { label: "Vonoj", emoji: "⏳" },
          { label: "Seen", emoji: "👀" },
          { label: "Ghost", emoji: "👻" },
          { label: "Kthej me meme", emoji: "🤣" },
          { label: "Harroj", emoji: "🤦" },
          { label: "I kthej natën", emoji: "🌙" },
          { label: "Varet nga mood-i", emoji: "🎭" },
        ],
      },
      {
        question: "Në shoqëri jam? 😏",
        options: [
          { label: "Lider", emoji: "👑" },
          { label: "Clown", emoji: "🤡" },
          { label: "I qetë", emoji: "😌" },
          { label: "I mistershëm", emoji: "🕶️" },
          { label: "Karizmatik", emoji: "✨" },
          { label: "I zhurmshëm", emoji: "🔊" },
          { label: "Observer", emoji: "👀" },
          { label: "I paparashikueshëm", emoji: "🎲" },
        ],
      },
      {
        question: "Sa dramatik jam? 🎭",
        options: [
          { label: "0%", emoji: "😐" },
          { label: "Pak", emoji: "🙂" },
          { label: "Shumë", emoji: "😅" },
          { label: "Ekstrem", emoji: "💥" },
          { label: "Vetëm për gallatë", emoji: "🤣" },
          { label: "Kur më kap nervi", emoji: "😤" },
        ],
      },
      {
        question: "Në debate bëj? 🔥",
        options: [
          { label: "Qetësi", emoji: "🕊️" },
          { label: "Argument", emoji: "🧠" },
          { label: "Shpërthej", emoji: "💣" },
          { label: "Iki", emoji: "🏃" },
          { label: "Tallje", emoji: "😏" },
          { label: "Ignoroj", emoji: "🙃" },
          { label: "Dominoj", emoji: "👑" },
          { label: "Qesh", emoji: "😂" },
        ],
      },
      {
        question: "Kur jam i lodhur? 😴",
        options: [
          { label: "Fle", emoji: "🛌" },
          { label: "Ankohem", emoji: "😩" },
          { label: "Humb", emoji: "😵" },
          { label: "Ha", emoji: "🍔" },
          { label: "Rri në telefon", emoji: "📱" },
          { label: "Bëhem nervoz", emoji: "😤" },
          { label: "Shtrihem", emoji: "🛋️" },
          { label: "Zhdukem", emoji: "👻" },
        ],
      },
      {
        question: "Si reagoj kur më pëlqen dikush? 😏",
        options: [
          { label: "Flas", emoji: "🗣️" },
          { label: "Shikoj", emoji: "👀" },
          { label: "Injoroj", emoji: "🙃" },
          { label: "Bëhem weird", emoji: "🤪" },
          { label: "Bëj sikur s’më intereson", emoji: "😎" },
          { label: "Bëhem funny", emoji: "😂" },
          { label: "I shkruaj", emoji: "💬" },
          { label: "Pres", emoji: "⏳" },
        ],
      },
      {
        question: "Sa funny jam realisht? 😂",
        options: [
          { label: "0", emoji: "😐" },
          { label: "Mesatar", emoji: "🙂" },
          { label: "Shumë", emoji: "😂" },
          { label: "Legjendë", emoji: "👑" },
          { label: "Varet nga dita", emoji: "📆" },
          { label: "Vetëm me njerëzit e mi", emoji: "🤝" },
        ],
      },
      {
        question: "Në chat jam? 💬",
        options: [
          { label: "Aktiv", emoji: "⚡" },
          { label: "Lazy", emoji: "🫠" },
          { label: "Ghost", emoji: "👻" },
          { label: "Spam", emoji: "📲" },
          { label: "Seen master", emoji: "👀" },
          { label: "Vetëm voice", emoji: "🎙️" },
          { label: "I ftohtë", emoji: "🧊" },
          { label: "Funny", emoji: "🤣" },
        ],
      },
      {
        question: "Kur jam i mërzitur? 😑",
        options: [
          { label: "Dal", emoji: "🚶" },
          { label: "Fle", emoji: "😴" },
          { label: "Scroll", emoji: "📱" },
          { label: "Qaj 😂", emoji: "😭" },
          { label: "Dëgjoj muzikë", emoji: "🎵" },
          { label: "Rri vetëm", emoji: "🌙" },
          { label: "Ha diçka", emoji: "🍟" },
          { label: "Bëj drive", emoji: "🚗" },
        ],
      },
    ],
  },
  {
    title: "Love",
    emoji: "❤️",
    questions: [
      {
        question: "Çfarë tipi më pëlqen? 💘",
        options: [
          { label: "Funny", emoji: "😂" },
          { label: "Romantik", emoji: "🌹" },
          { label: "Serioz", emoji: "🖤" },
          { label: "Crazy", emoji: "🤪" },
          { label: "Karizmatik", emoji: "✨" },
          { label: "I qetë", emoji: "😌" },
          { label: "I zgjuar", emoji: "🧠" },
          { label: "Dominant", emoji: "🔥" },
        ],
      },
      {
        question: "Çfarë vlerësoj më shumë? ✨",
        options: [
          { label: "Besnikëri", emoji: "🤍" },
          { label: "Bukuri", emoji: "😍" },
          { label: "Humor", emoji: "😂" },
          { label: "Ambicie", emoji: "🚀" },
          { label: "Respekt", emoji: "🫶" },
          { label: "Sinqeritet", emoji: "🪞" },
          { label: "Qetësi", emoji: "🌙" },
          { label: "Vëmendje", emoji: "💌" },
        ],
      },
      {
        question: "Date ideal për mua? 🌙",
        options: [
          { label: "Darkë", emoji: "🍽️" },
          { label: "Kafe", emoji: "☕" },
          { label: "Shetitje", emoji: "🚶‍♀️" },
          { label: "Netflix", emoji: "📺" },
          { label: "Det", emoji: "🌊" },
          { label: "Drive natën", emoji: "🚗" },
          { label: "Kinema", emoji: "🎬" },
          { label: "Picnic", emoji: "🧺" },
        ],
      },
      {
        question: "Çfarë më tërheq më shumë? 👀",
        options: [
          { label: "Sytë", emoji: "👀" },
          { label: "Buzëqeshja", emoji: "😁" },
          { label: "Stili", emoji: "🕶️" },
          { label: "Sjellja", emoji: "🤍" },
          { label: "Zëri", emoji: "🎙️" },
          { label: "Energjia", emoji: "⚡" },
          { label: "Karizma", emoji: "✨" },
          { label: "Mendja", emoji: "🧠" },
        ],
      },
      {
        question: "Si bie në dashuri? 😏",
        options: [
          { label: "Shpejt", emoji: "⚡" },
          { label: "Ngadalë", emoji: "🌙" },
          { label: "Me zor", emoji: "😶" },
          { label: "S’bie fare", emoji: "🧊" },
          { label: "Kur ndihem safe", emoji: "🫶" },
          { label: "Kur më kuptojnë", emoji: "🤍" },
        ],
      },
      {
        question: "Xhelozia ime është? 😅",
        options: [
          { label: "0%", emoji: "😌" },
          { label: "Pak", emoji: "🙂" },
          { label: "Mesatare", emoji: "😅" },
          { label: "Shumë", emoji: "😤" },
          { label: "Varet nga personi", emoji: "👀" },
          { label: "S’e tregoj", emoji: "🤐" },
        ],
      },
      {
        question: "Në lidhje jam? ❤️",
        options: [
          { label: "Serioz", emoji: "🖤" },
          { label: "Funny", emoji: "😂" },
          { label: "Dominant", emoji: "🔥" },
          { label: "Chill", emoji: "😌" },
          { label: "Romantik", emoji: "🌹" },
          { label: "Protective", emoji: "🛡️" },
          { label: "I thellë", emoji: "🌙" },
          { label: "Pak i komplikuar", emoji: "🌀" },
        ],
      },
      {
        question: "Çfarë më lëndon më shumë? 💔",
        options: [
          { label: "Gënjeshtra", emoji: "🤥" },
          { label: "Tradhtia", emoji: "💔" },
          { label: "Injorimi", emoji: "🙄" },
          { label: "Ftohtësia", emoji: "🧊" },
          { label: "Mosrespekti", emoji: "🚫" },
          { label: "Mungesa e vëmendjes", emoji: "📭" },
        ],
      },
      {
        question: "Çfarë dua realisht? 🤍",
        options: [
          { label: "Dashuri", emoji: "❤️" },
          { label: "Qetësi", emoji: "🕊️" },
          { label: "Attention", emoji: "👀" },
          { label: "Eksitim", emoji: "🔥" },
          { label: "Besnikëri", emoji: "🤍" },
          { label: "Stabilitet", emoji: "🏡" },
          { label: "Passion", emoji: "💋" },
          { label: "Mirëkuptim", emoji: "🫶" },
        ],
      },
      {
        question: "A dashurohem lehtë? 😶",
        options: [
          { label: "Po", emoji: "❤️" },
          { label: "Jo", emoji: "🧊" },
          { label: "Ndonjëherë", emoji: "🌙" },
          { label: "Varet", emoji: "🎭" },
          { label: "Vetëm kur lidhem fort", emoji: "🤍" },
        ],
      },
    ],
  },
  {
    title: "Lifestyle",
    emoji: "✨",
    questions: [
      {
        question: "Stili im i preferuar është? 👕",
        options: [
          { label: "Sport", emoji: "👟" },
          { label: "Elegant", emoji: "🤵" },
          { label: "Street", emoji: "🧢" },
          { label: "Minimal", emoji: "🤍" },
          { label: "Luxury", emoji: "💎" },
          { label: "Casual", emoji: "🙂" },
          { label: "Dark", emoji: "🖤" },
          { label: "Trendy", emoji: "✨" },
        ],
      },
      {
        question: "Ora ime ideale për të dalë? 🌆",
        options: [
          { label: "Paradite", emoji: "🌤️" },
          { label: "Pasdite", emoji: "☀️" },
          { label: "Mbrëmje", emoji: "🌆" },
          { label: "Natë vonë", emoji: "🌙" },
        ],
      },
      {
        question: "Pushimi ideal për mua? 🌴",
        options: [
          { label: "Det", emoji: "🌊" },
          { label: "Mal", emoji: "⛰️" },
          { label: "Qytet", emoji: "🏙️" },
          { label: "Resort", emoji: "🏝️" },
          { label: "Fshat", emoji: "🌾" },
          { label: "Road trip", emoji: "🚗" },
        ],
      },
      {
        question: "Pija ime e preferuar? 🥤",
        options: [
          { label: "Kafe", emoji: "☕" },
          { label: "Red Bull", emoji: "⚡" },
          { label: "Lëng", emoji: "🧃" },
          { label: "Ujë", emoji: "💧" },
          { label: "Coca-Cola", emoji: "🥤" },
          { label: "Milkshake", emoji: "🍨" },
          { label: "Çaj", emoji: "🍵" },
          { label: "Smoothie", emoji: "🍓" },
        ],
      },
      {
        question: "Zgjohem zakonisht? ⏰",
        options: [
          { label: "Herët", emoji: "🌅" },
          { label: "Mesatarisht", emoji: "🙂" },
          { label: "Vonë", emoji: "😴" },
          { label: "Shumë vonë", emoji: "🛌" },
        ],
      },
      {
        question: "Çfarë zgjedh më shpesh? 🍔",
        options: [
          { label: "Fast food", emoji: "🍔" },
          { label: "Home food", emoji: "🍲" },
          { label: "Sweet", emoji: "🍰" },
          { label: "Healthy", emoji: "🥗" },
          { label: "Snack", emoji: "🍟" },
          { label: "Random", emoji: "🎲" },
        ],
      },
      {
        question: "Më pëlqen më shumë? 🚗",
        options: [
          { label: "Makina", emoji: "🚘" },
          { label: "Moto", emoji: "🏍️" },
          { label: "Bicikleta", emoji: "🚲" },
          { label: "Ecja", emoji: "🚶" },
          { label: "Transport luksoz", emoji: "✨" },
          { label: "Drive i gjatë", emoji: "🛣️" },
        ],
      },
      {
        question: "Muzika ime vibe? 🎵",
        options: [
          { label: "Rap", emoji: "🎤" },
          { label: "Pop", emoji: "🎶" },
          { label: "House", emoji: "🔊" },
          { label: "Mixed", emoji: "🎧" },
          { label: "R&B", emoji: "💜" },
          { label: "Trap", emoji: "🔥" },
          { label: "Slow", emoji: "🌙" },
          { label: "Club", emoji: "💃" },
        ],
      },
      {
        question: "Platforma që përdor më shumë? 📱",
        options: [
          { label: "TikTok", emoji: "🎵" },
          { label: "Instagram", emoji: "📸" },
          { label: "Snapchat", emoji: "👻" },
          { label: "YouTube", emoji: "▶️" },
          { label: "WhatsApp", emoji: "💬" },
          { label: "Spotify", emoji: "🎧" },
        ],
      },
      {
        question: "Mbrëmja perfekte për mua? 🌙",
        options: [
          { label: "Party", emoji: "🎉" },
          { label: "Netflix", emoji: "📺" },
          { label: "Drive", emoji: "🚗" },
          { label: "Darkë", emoji: "🍽️" },
          { label: "Shëtitje", emoji: "🚶" },
          { label: "Gaming", emoji: "🎮" },
          { label: "Me njerëzit e mi", emoji: "🤝" },
          { label: "Vetëm", emoji: "🌙" },
        ],
      },
    ],
  },
  {
    title: "Social",
    emoji: "🧠",
    questions: [
      {
        question: "Në grup zakonisht jam? 👥",
        options: [
          { label: "Lider", emoji: "👑" },
          { label: "Funny", emoji: "😂" },
          { label: "I qetë", emoji: "😌" },
          { label: "Vëzhgues", emoji: "👀" },
          { label: "Organizator", emoji: "📋" },
          { label: "Dominant", emoji: "🔥" },
          { label: "I rezervuar", emoji: "🤐" },
          { label: "Energjia e grupit", emoji: "⚡" },
        ],
      },
      {
        question: "Kur më njeh dikush për herë të parë? 👀",
        options: [
          { label: "Dukem serioz", emoji: "🧠" },
          { label: "Dukem chill", emoji: "😌" },
          { label: "Dukem funny", emoji: "😂" },
          { label: "Dukem i ftohtë", emoji: "🧊" },
          { label: "Dukem karizmatik", emoji: "✨" },
          { label: "Dukem misterioz", emoji: "🌙" },
        ],
      },
      {
        question: "Miqtë më kërkojnë për? 📞",
        options: [
          { label: "Këshillë", emoji: "🧠" },
          { label: "Gallatë", emoji: "😂" },
          { label: "Zgjidhje", emoji: "✅" },
          { label: "Shoqëri", emoji: "🤝" },
          { label: "Mbështetje", emoji: "🫶" },
          { label: "Dalje", emoji: "🎉" },
        ],
      },
      {
        question: "Si sillem në debate? 🥊",
        options: [
          { label: "Qetë", emoji: "🕊️" },
          { label: "Fort", emoji: "🔥" },
          { label: "Me ironi", emoji: "😏" },
          { label: "S’merrem", emoji: "🙃" },
          { label: "Mbroj veten", emoji: "🛡️" },
          { label: "Dominoj bisedën", emoji: "👑" },
        ],
      },
      {
        question: "Në chat jam? 💬",
        options: [
          { label: "Shpejt", emoji: "⚡" },
          { label: "Vonë", emoji: "⏳" },
          { label: "Seen", emoji: "👀" },
          { label: "Mood", emoji: "🎭" },
          { label: "Funny", emoji: "😂" },
          { label: "I shkurtër", emoji: "✂️" },
        ],
      },
      {
        question: "Kur dikush më bezdis? 😤",
        options: [
          { label: "Shpërthej", emoji: "💥" },
          { label: "Hesht", emoji: "🤐" },
          { label: "I shmangem", emoji: "🚶" },
          { label: "Tallje", emoji: "😏" },
          { label: "Bllokoj", emoji: "⛔" },
          { label: "E mbaj brenda", emoji: "🫥" },
        ],
      },
      {
        question: "Çfarë energjie jap? ⚡",
        options: [
          { label: "Calm", emoji: "🕊️" },
          { label: "Crazy", emoji: "🤪" },
          { label: "Boss", emoji: "👑" },
          { label: "Mystery", emoji: "🌙" },
          { label: "Positive", emoji: "☀️" },
          { label: "Dark", emoji: "🖤" },
        ],
      },
      {
        question: "Më përshkruajnë si? 🔥",
        options: [
          { label: "Karizmatik", emoji: "✨" },
          { label: "I fortë", emoji: "💪" },
          { label: "I veçantë", emoji: "🌟" },
          { label: "Funny", emoji: "😂" },
          { label: "Dominant", emoji: "🔥" },
          { label: "I zgjuar", emoji: "🧠" },
          { label: "I qetë", emoji: "😌" },
          { label: "Misterioz", emoji: "🌙" },
        ],
      },
      {
        question: "Në dalje me shoqëri jam? 🍻",
        options: [
          { label: "Organizator", emoji: "📋" },
          { label: "Qendra e vëmendjes", emoji: "🎯" },
          { label: "Chill", emoji: "😌" },
          { label: "Zhdukem", emoji: "👻" },
          { label: "I heshtur", emoji: "🤐" },
          { label: "Duke qeshur gjithë kohën", emoji: "🤣" },
        ],
      },
      {
        question: "Sa shpejt afrohem me njerëz? 🤝",
        options: [
          { label: "Shumë shpejt", emoji: "⚡" },
          { label: "Normal", emoji: "🙂" },
          { label: "Ngadalë", emoji: "🌙" },
          { label: "Vështirë", emoji: "🧱" },
          { label: "Varet nga energjia", emoji: "✨" },
        ],
      },
    ],
  },
  {
    title: "Deep",
    emoji: "🌙",
    questions: [
      {
        question: "Frika ime më e madhe është? 🌑",
        options: [
          { label: "Vetmia", emoji: "🌑" },
          { label: "Dështimi", emoji: "📉" },
          { label: "Tradhtia", emoji: "💔" },
          { label: "Humbja", emoji: "🥀" },
          { label: "Mosarritja", emoji: "🫥" },
          { label: "Të lëndoj njerëzit e mi", emoji: "🤍" },
        ],
      },
      {
        question: "Çfarë vlerësoj më shumë në jetë? 🤍",
        options: [
          { label: "Familjen", emoji: "👨‍👩‍👧‍👦" },
          { label: "Lirinë", emoji: "🕊️" },
          { label: "Dashurinë", emoji: "❤️" },
          { label: "Suksesin", emoji: "🏆" },
          { label: "Paqen", emoji: "☁️" },
          { label: "Besnikërinë", emoji: "🤝" },
        ],
      },
      {
        question: "Kur jam keq, zakonisht? 😶",
        options: [
          { label: "Hesht", emoji: "🤐" },
          { label: "Flas", emoji: "🗣️" },
          { label: "Dal", emoji: "🚶" },
          { label: "Zhdukem", emoji: "👻" },
          { label: "Dëgjoj muzikë", emoji: "🎵" },
          { label: "Qëndroj vetëm", emoji: "🌙" },
        ],
      },
      {
        question: "Çfarë më prek më shumë? 💭",
        options: [
          { label: "Fjalët", emoji: "🗣️" },
          { label: "Veprimet", emoji: "🤝" },
          { label: "Mungesa", emoji: "🫥" },
          { label: "Gënjeshtrat", emoji: "🤥" },
          { label: "Mosrespekti", emoji: "🚫" },
          { label: "Ftohtësia", emoji: "🧊" },
        ],
      },
      {
        question: "Si e ruaj veten? 🛡️",
        options: [
          { label: "Distancë", emoji: "📏" },
          { label: "Humor", emoji: "😂" },
          { label: "Ftohtësi", emoji: "🧊" },
          { label: "Kontroll", emoji: "🎯" },
          { label: "Heshtje", emoji: "🤐" },
          { label: "Mbyllje emocionale", emoji: "🚪" },
        ],
      },
      {
        question: "Çfarë kërkoj te njerëzit? ✨",
        options: [
          { label: "Sinqeritet", emoji: "🪞" },
          { label: "Besnikëri", emoji: "🤍" },
          { label: "Respekt", emoji: "🫶" },
          { label: "Qetësi", emoji: "🕊️" },
          { label: "Mirëkuptim", emoji: "🤝" },
          { label: "Energji të pastër", emoji: "✨" },
        ],
      },
      {
        question: "Kur mendoj shumë? 🌌",
        options: [
          { label: "Natën", emoji: "🌙" },
          { label: "Kur jam vetëm", emoji: "🖤" },
          { label: "Kur jam keq", emoji: "🥀" },
          { label: "Gjithmonë", emoji: "♾️" },
          { label: "Kur më mungon diçka", emoji: "💭" },
        ],
      },
      {
        question: "Çfarë më jep paqe? 🕊️",
        options: [
          { label: "Qetësia", emoji: "☁️" },
          { label: "Muzika", emoji: "🎵" },
          { label: "Deti", emoji: "🌊" },
          { label: "Njerëzit e afërt", emoji: "🤍" },
          { label: "Makina/drive", emoji: "🚗" },
          { label: "Vetmia", emoji: "🌙" },
        ],
      },
      {
        question: "Çfarë lëndon më shumë tek unë? 💔",
        options: [
          { label: "Tradhtia", emoji: "💔" },
          { label: "Mosrespekti", emoji: "🚫" },
          { label: "Injorimi", emoji: "🙄" },
          { label: "Humbja", emoji: "🥀" },
          { label: "Fjalët e rënda", emoji: "🗡️" },
          { label: "Mungesa e vlerësimit", emoji: "📉" },
        ],
      },
      {
        question: "Në fund të ditës dua? 🌙",
        options: [
          { label: "Qetësi", emoji: "🕊️" },
          { label: "Dashuri", emoji: "❤️" },
          { label: "Sukses", emoji: "🏆" },
          { label: "Stabilitet", emoji: "🏡" },
          { label: "Paqe mendore", emoji: "☁️" },
          { label: "Njerëzit e mi afër", emoji: "🤍" },
        ],
      },
    ],
  },
];